# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  username: root
  password: root
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: employee_info

production:
  <<: *default
  database: employee_info
